# © 2020 Joseph Cameron - All Rights Reserved
# jfc-wanikani_reviews_icon ci script

dist: bionic 
sudo: required
language: cpp

matrix:
  include:
    # Build scripts
    - os: linux
      name: build linux gcc
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - git
            - libgtk-3-dev
            - curl
            - gcc-8
            - g++-8
      script:
        - |
          export CC=/usr/bin/gcc-8
          export CXX=/usr/bin/g++-8
          git submodule update --init --recursive
          cd workspace
          cmake .. -DJFC_BUILD_DOCS=OFF -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Ofast -flto -funroll-loops -m64 -march=native -Wno-deprecated-declarations"
          cmake --build .
          # ctest --extra-verbose
          
before_script: 
  - |
    CURRENT_COMMIT_HASH="$(git rev-parse HEAD)"
